services:
  spark-master:
    image: bitnami/spark:3.4.3
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_USER_NAME=root
      - spark.hadoop.security.authentication=simple
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./opt/shared:/opt/shared
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spark-master:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker-1:
    image: bitnami/spark:3.4.3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./opt/shared:/opt/shared
    depends_on:
      - spark-master
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spark-master:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker-2:
    image: bitnami/spark:3.4.3
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./opt/shared:/opt/shared
    depends_on:
      - spark-master
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spark-master:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra:
    image: cassandra:4.0.13
    container_name: cassandra-container
    ports:
      - "7199:7199"
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q 'UN'"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  my-network:
    driver: bridge
